# IC-GVINS

# Output directory
outputpath: "/home/vdcl/Documents/gvins_output"
is_make_outputdir: true

# Time length for GNSS/INS intialization, sec
initlength: 1

# IMU sample rate, hz
imudatarate: 100

# Consider the Earth rotation
iswithearth: true

# GNSS lever-arm in IMU body frame (front-right-down) meter
antlever: [0.0, 0.0, 0.0] 

# IMU noise parameters
imumodel:
    arw: 0.2        # deg/sqrt(hr)
    vrw: 0.005        # m/s/sqrt(hr)
    gbstd: 2.0     # deg/hr
    abstd: 1.96133     # mGal
    corrtime: 1.0   # hr

# GNSS outage configurations, the GNSS will not be used after the gnssoutagetime 
isusegnssoutage: false
gnssoutagetime: 0

# A fixed threshold (STD, m) for GNSS outlier culling
gnssthreshold: 5

# Use visualization
is_use_visualization: true

# Tracking configurations
track_check_histogram: false    # (Check histogram for drastic illumulation change)
track_min_parallax: 20          # (The minmum parallax in pixels to choose a keyframe)
track_max_interval: 0.5         # (The maximum length to choose a observation frame) sec
track_max_features: 200         # (The maximum features to detect, may be more or less, see tracking.cc)

# Optimization configurations
reprojection_error_std: 1.5         # (The reprojection error std for optimizition and outlier culling)
optimize_windows_size: 10           # (The size of the sliding window, number of the keyframes )
optimize_num_iterations: 20         # (The iterations in total)
optimize_estimate_extrinsic: false   # (Estimate the extrinsic)
optimize_estimate_td: false          # (Estimate the time delay)

# Camera parameters
cam0:
    # Intrinsic parameters, pinhole model fx, fy, cx, cy
    intrinsic: [1364, 1364, 512, 288]

    # Distortion parameters k1, k2, p1, p2
    distortion: [-0.023932, 0.037017, -0.000308, -0.006870]

    # Resolution
    resolution: [1024, 576]

    # (Camera-IMU extrinsic)
    # Pb = q_b_c * Pc + t_b_c
    # q (x, y, z, w)
    q_b_c: [0.4945, 0.4978, 0.5056, 0.5020]
    t_b_c: [4.843, 0.2, -2.2]

    # (The time delay between the IMU and camera)
    # t_i = t_c + td
    td_b_c: 0.0
